Fix MACOSX deployment target (#381)

diff --git a/.github/workflows/wheel.yml b/.github/workflows/wheel.yml
--- a/.github/workflows/wheel.yml
+++ b/.github/workflows/wheel.yml
@@ -120,7 +120,7 @@ jobs:
 
     defaults:
       run:
-        shell: bash -l {0}
+        shell: bash -l -eo pipefail {0}
 
     steps:
       # Set up Python to host 'cibuildwheel'
@@ -137,6 +137,21 @@ jobs:
         uses: actions/download-artifact@v8
         with:
           name: dftd4-python-sdist
+
+      # Determine macOS version for CIBW deployment target
+      - name: Determine macOS Deployment Target
+        if: contains(matrix.os, 'macos')
+        run: |
+          VERSION="$(sw_vers -productVersion | cut -d. -f1)"
+          
+          # Check if empty before injecting it into environment
+          if [[ -z "$VERSION" ]]; then
+            echo "::error::Failed to determine macOS version"
+            exit 1
+          fi
+          
+          echo "DYNAMIC_MACOS_TARGET=${VERSION}.0" >> $GITHUB_ENV
+          echo "macOS version determined: ${VERSION}.0"
 
       # Build wheels for all supported Python versions
       - name: Build wheels
@@ -165,6 +180,8 @@ jobs:
             brew install gcc@14 openblas@0.3.23
             rm -f /usr/local/lib/libgfortran*.dylib
 
+          MACOSX_DEPLOYMENT_TARGET: ${{ env.DYNAMIC_MACOS_TARGET }}
+
           # Set macOS variables to find gfortran, lapack, and avoid testing 
           # against macOS earlier than 14 (see above)
           CIBW_ENVIRONMENT_MACOS: >
@@ -172,7 +189,7 @@ jobs:
             PKG_CONFIG_PATH="$(brew --prefix openblas)/lib/pkgconfig"
             LDFLAGS="-L$(brew --prefix openblas)/lib -L$(brew --prefix gcc@14)/lib/gcc/14"
             CPPFLAGS="-I$(brew --prefix openblas)/include"
-            MACOSX_DEPLOYMENT_TARGET=${{ matrix.os == 'macos-15-intel' && '15.0' || '15.0' }}
+            MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET}"
 
           # Additional debug delocate command for finding duplicate libraries
           CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
